### ISSUE TITLE
PCLOpenXML uses vendor-specific `<addData>`

### ISSUE THREAD

**Issue by wadoon** [SafaBoug/xPPU_Model_Share#2]
The PCLOpenXML is exported in such a way, that all POUs or data types are in the extension fields `<addData` and not in their XML tags, like `<pou>`. 

This happens (in CodeDevSys)  if some non-standard element  is exported in the XML file.

**Comment by SafaBoug** [comment]
The vendor-specific tags in the ( PLCOpenXML ) for the non standard elements are in there because we use TwinCAT3
